### ISSUE TITLE
请问有chapter2.tex参考文献的代码吗？

### ISSUE THREAD

**Issue by a5corpii** [gaorongchao/Latex_Liu#1]
也在学习TeX，其余的部分都能生成，惟有参考文献不能正常加载。

找到了这个repo却没有`\bibliography{math}`的部分。

谢谢！

**Comment by a5corpii** [comment]
偶然往后翻看一下，参考文献有关的章节已经介绍了，只编译 .tex 文件是不行的，需要这样：

1. xelatex c.tex
2. bibtex c.aux
3. xelatex c.tex
4. xelatex c.tex

即可。

**Comment by gaorongchao** [comment]
谢谢！
